version: '3.8'

services:
  lightrag:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - TZ=UTC
    restart: unless-stopped
    networks:
      - lightrag_net
networks:
  lightrag_net:
    driver: bridge