services:
  lightrag:
    build:
      context: .
      dockerfile: Dockerfile
    image: minirag-image:latest
    container_name: minirag-container
    environment:
      - TZ=Asia/Tokyo
    restart: unless-stopped
    networks:
      - lightrag_net
networks:
  lightrag_net:
    driver: bridge